### ISSUE TITLE
mshtml-sessionStorage patches do not longer apply

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#119]
The new wine gecko update introduced some changes which broke the mshtml-sessionStorage patches in a non trivial way. @slackner disabled the patches for now, but the author Zhenbo Li (@endle) needs to fix them till the next release or we need to remove them again.

**Comment by slackner** [comment]
The old patchset was removed with ffac1eec98fcc795179ca8bc329a46c8dad35dc3. Since it didn't apply anymore it was useless anyway.

@endle: If you find a way to reimplement the same functionality, which is compatible with recent versions of Gecko please submit a new patch on our [new bug tracker](https://bugs.wine-staging.com/describecomponents.cgi).
