### ISSUE TITLE
Add testing environment for drivers

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#178]
There is nothing to test ntoskrnl.exe and .sys drivers.
- Contrary to wine tests. You need a combination of a test drivers .sys and a test application .exe to achieve that.
- kernel drivers need to be build on Windows. It seems mingw supports that. See links below.

https://myworks2012.wordpress.com/2012/10/07/how-to-compile-windows-driver-using-mingw-gcc
http://www.fccps.cz/download/adv/frr/win32_ddk_mingw/win32_ddk_mingw.html

**Comment by slackner** [comment]
Voila, here it is: http://ix.io/fPH
Needs `autoreconf -f`.

I haven't added it directly because it does a lot of changes in all parts of Wines Makefile system. Please give the patch a try on various distributions and with various ./configure options (`--disable-tests` for example). If everything works well for all major distributions, then I'll add it before the next release. If possible also check manually the generated Makefiles (dlls/ntoskrnl.exe/tests and dlls/ntoskrnl.exe/tests/driver.sys).

Note1: I have also added @DarkPlayer and @titan73 into the copyright, because I reused a lot of code above.

Note2: I am not completely happy yet because somehow on Wine the driver never unloads properly... Patches welcome! ;)

**Comment by slackner** [comment]
Sry, forgot to add one file to the patch. Fixed version: http://ix.io/fPL

**Comment by titan73** [comment]
Nice! I'll git it a try.

**Comment by titan73** [comment]
Tested w/ and w/o --disable-tests. Compile fine here.
Tested both test and cross test. Everything works fine.
Good job!

**Comment by titan73** [comment]
My system is Ubuntu 14.10.

**Comment by fracting** [comment]
Thanks for the great work!

Compiles fine here on Ubuntu 14.10 i386.
Tested:
* make and make clean with --disable-tests
* make and make clean without --disable-test
* make crosstest from test directory
* make crosstest from source root directory.

All these above work fine here.

Note that `make depend` is required before make, other wise I may get error like below:

make[1]: Entering directory '/media/workspace/src/wine-git/dlls/ntoskrnl.exe/tests'
i686-w64-mingw32-gcc -c -o ntoskrnl.cross.o ntoskrnl.c -I. -I../../../include -D__WINESRC__ -DWINE_CROSSTEST -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
i686-w64-mingw32-gcc -c -o testlist.cross.o testlist.c -I. -I../../../include -D__WINESRC__ -DWINE_CROSSTEST -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
make -C driver.sys driver_crossres.sys
make[2]: Entering directory '/media/workspace/src/wine-git/dlls/ntoskrnl.exe/tests/driver.sys'
make[2]: *** No rule to make target 'driver_crossres.sys'。 停止。
make[2]: Leaving directory '/media/workspace/src/wine-git/dlls/ntoskrnl.exe/tests/driver.sys'
Makefile:204: recipe for target 'driver.sys/driver_crossres.sys' failed
make[1]: *** [driver.sys/driver_crossres.sys] Error 2
make[1]: Leaving directory '/media/workspace/src/wine-git/dlls/ntoskrnl.exe/tests'
Makefile:13457: recipe for target 'dlls/ntoskrnl.exe/tests/crosstest' failed
make: *** [dlls/ntoskrnl.exe/tests/crosstest] Error 2

Can't wait for the merge!

**Comment by titan73** [comment]
I did some measurement and the service takes 5 mn to stop on wine.
I was not able to measure the timeout on windows as the test does not work:
```
C:\>ntoskrnl.exe_crosstest.exe
ntoskrnl.c:219: Tests skipped: Failed to load driver, skipping tests.
ntoskrnl: 0 tests executed (0 marked as todo, 0 failures), 1 skipped.
```
The windows version is:
Windows 7 Familial Edition Premium
Service Pack 1
It's 64 bit. Maybe windows cannot load a 32 bit driver.

**Comment by DarkPlayer** [comment]
You can not load a 32 bit driver into a 64 bit Window version. You will need to use `make crosstest` when Wine is configured using `--enable-win64` in order to get a 64 bit test and driver. However, Windows 64 bit has driver signing turned on by default and will not load any drivers that are not indirectly signed by microsoft. You will need to turn if off again in order to load the driver.

**Comment by DarkPlayer** [comment]
I just tested the patch and I think we should fix `ntoskrnl.exe_crosstest.exe` and even more ugly `ntoskrnl.exe_test.exe.so`. My original code changed the behavior to strip all extensions and not only .dll like the current wine code does. Except that you need a utility function to split the filename correctly, this was a one line change. Is there any reason @slackner why you dropped this change?

I just tested the crosstest on the following systems:
```
Windows XP 32 Bit: OK
Windows 10 32 Bit: OK
Windows 10 64 Bit: FAIL
```

The driver can not be loaded on Windows 10 64 bit even after disabling the driver signature check (which is btw. ridiculously complicated on newer windows versions). The windows event log contains the following message:
```
The WineTestDriver service failed to start due to the following error: 
The data area passed to a system call is too small.
```

Seems like a structure definition in Wine is not compatible with Win 10 64 bit or we are passing a wrong buffer.

I tried to debug the problem using windbg from the Windows Driver Development kit, but it does not contain symbols for Windows 10 and we also do not have any symbols for the driver. This makes it quite hard to use windbg. However, it seems that our driver is not loaded at all, since I didn't get the `loading driver` message with DebugView on Windows 64 bit.

**Comment by DarkPlayer** [comment]
I just saw that the driver signature check became active again, so my last statement might be wrong.

**Comment by slackner** [comment]
@fracting: Thanks for pointing out this issue. I guess this can be seen as a bug in my current implementation. Wines Makefile system also contains the same issue (for example with programs/winetest), but the chances are much smaller that you'll trigger it. I'll check whats the best way to fix that.

Thanks for testing everyone! :)

**Comment by titan73** [comment]
I recompile in 64 bit and disabled signing and I get:
```
ntoskrnl.c:150: Trying to load driver C:\Users\titan\AppData\Local\Temp\drv560B.tmp
ntoskrnl.c:199: Test failed: Connecting to driver failed with 2
ntoskrnl.c:111: Test failed: expected SERVICE_STOPPED, got 4
ntoskrnl: 5 tests executed (0 marked as todo, 2 failures), 0 skipped.
```
If I retry I get:
```
C:\>ntoskrnl.exe_crosstest.exe
ntoskrnl.c:150: Trying to load driver C:\Users\titan\AppData\Local\Temp\drv560B.tmp
ntoskrnl.c:199: Test failed: Connecting to driver failed with 2
ntoskrnl.c:111: Test failed: expected SERVICE_STOPPED, got 4
ntoskrnl: 5 tests executed (0 marked as todo, 2 failures), 0 skipped.
```

**Comment by DarkPlayer** [comment]
@titan73 Take a look at the System event log, you most probably get the same error message.

**Comment by titan73** [comment]
The system events log  just says the driver has been loaded successfully but I have not error.

**Comment by DarkPlayer** [comment]
Hmm, maybe Windows 10 is a bit special, but I didn't have any other Windows 64 bit system installed as VM. Btw, did someone already try to run the tests on the Testbot? ;-)

**Comment by titan73** [comment]
Yep @slackner did it https://newtestbot.winehq.org/JobDetails.pl?Key=11198&log_103=1#k103.

**Comment by titan73** [comment]
Btw @DarkPlayer did you the unload problem on windows ? Were you able to launch successfully launch the test several time?

**Comment by DarkPlayer** [comment]
@titan73 For me the driver test works without issues on Windows XP. I can execute the tests as often as I want without any waiting time.

We are getting one step closer to our goal. I worked on a standard way of executing kernel tests and tried to port the wine test commands so that you can use them inside of the kernel. I need to clean it up a bit and I might also change some stuff, but here is how a kernel test now looks like:

```c
BEGIN_TEST(test1, struct test1_input)
{
    int i;
    const char str[] = "Wine is not an emulator";

    for (i = 0; i < sizeof(str)-1; i++)
        input->buf[i] = str[i];

    ok(0, "Something failed: %d!\n", 42);
    skip("This driver is lazy and skips a test!\n");
    trace("Just a useless trace message...\n");

    return STATUS_SUCCESS;
}
```

The second parameter (`struct test1_input`) defines the input type for this test. The passed data is accessible through the `input` variable and is used to exchange values with the userland process. The changes of the structure are copied back to the userland process, so it behaves like a reference parameter. The `BEGIN_TEST` macro also checks the size of the passed buffer to prevent crashes in the kernel.

Here is the output when running this test on Windows:
```
ntoskrnl.c:150: Trying to load driver C:\DOKUME~1\Dark\LOKALE~1\Temp\drv16.tmp
driver.c:49: Test failed: Something failed: 42!
driver.c:50: Tests skipped: This driver is lazy and skips a test!
driver.c:51: Just a useless trace message...
ntoskrnl: 8 tests executed (0 marked as todo, 1 failure), 1 skipped.
``` 

If we get the remaining Makefile issues fixed, chances are good that we can add this feature before the next release.

**Comment by titan73** [comment]
Nice ! Good job!

**Comment by titan73** [comment]
Btw. Since the driver unload fine on Windows that means services does not work very well in wine then.

**Comment by DarkPlayer** [comment]
I finished most of the wine test functions and uploaded the patch:
https://dl.dropboxusercontent.com/u/61413222/0001-ntoskrnl.exe-tests-Add-kernel-compliant-test-functio.patch

You need to apply it on top of @slackner patch (http://ix.io/fPH). The test functions basically behave the same way as the usual test functions but they can not be used at all places. They require to pass some data between userland and kernel and therefore you can not use them if you want to explicitly define the input / output for `DeviceIoControl`.

By default you can only use the test functions inside of functions defined by `BEGIN_TEST`. If you want to call other functions (which use test functions) from within a `BEGIN_TEST` function, you need to pass the __input variable to these functions as parameter (`struct _kernel_test_data* __input`). The test macros expect this variable to be available in order to read and store information about the executed tests.

**Comment by slackner** [comment]
---> Revision 2: http://ix.io/fUX
This contains both commits, my initial commit and also a cleaned up version of @DarkPlayer's work, If noone experiences any additional critical problems (with the Make system changes) it will be added with 1.7.35. Also feel free to contribute additional testcases, which can also be added at the same time (I am more concerned about the Make stuff ^^).

For those planning to contribute additional tests, this is how it basically works: http://ix.io/fUY
Step by step:

* You need to define an IOCTL `WINE_IOCTL_<testname>` with a (small) number. Each number should be only used exactly once.

* You need to define a `test_<testname>_state` structure. The first element should always be `struct kernel_test_state __state;`. This structure is used for both input and output of kernel data, and behaves very similar to shared memory. Define arbitrary additional fields to pass data to the kernel or back to usermode. Make sure to initialize data if necessary.

* In driver_IoControl you need to forward the IOCTL to the specific testcase. This can be done with `DECLARE_TEST(<testname>)`.

* Define a test function with `KERNEL_TESTCASE(<testname>)`. The values in your state structure are available with `test->`. This is where @DarkPlayer's work is very useful - you can directly use various functions like `todo_wine`, `ok`, `win_skip`, ... These messages and also test failures will be passed back to the user mode application and appear like any other failure - except you manage to crash the kernel. ;) When your testcases produces too much output it will be truncated, and an additional testfailure will be counted. I am not yet completely sure if it should really be a testfailure or just a warning, but as long as we do not have any tests which produce huge amount of output, it will not matter anyway. Please note that the `KERNEL_TESTCASE` macro does a lot additional work behind the scenes, like validating input or clearing the memory used for temporary variables.

* On the usermode side you create a new function which connects to the driver, and then uses `wine_run_kernel_test` to execute the test. Make sure to pass always a struct of the appropriate type to each IOCTL. This function will automatically print the kernel debug buffer, and also count all kernel test failures / skips / ... appropriately.

Note: It will be impossible to use all of these helper functions for every single test. In order to test for example specific error handling / explicit invalid behaviour it might be necessary to implement it differently, which is also perfectly fine. Nevertheless, I am pretty sure that we'll also have a lot of tests which fit into this pattern.

**Comment by slackner** [comment]
Still seems to work on the 32-bit testbot: http://newtestbot.winehq.org/JobDetails.pl?Key=11253&log_101=1#k101 (not finished yet)

**Comment by fracting** [comment]
Thanks for the improvement, now `make crosstest` works without manually `make depend` here.

**Comment by slackner** [comment]
With minor changes added in 29bbba1e0f6bea423a41b186ad45cdd04b1dae72 :)
Have fun, and feel free to add tests for all future patchsets implementing ntoskrnl stuff ^^
