### ISSUE TITLE
World of Warcraft: Can't click buttons at the lower edge of the screen

### ISSUE THREAD

**Issue by yoshimo** [wine-compholio/wine-staging#188]
I am running the staging build of wine 1.7.31  and tried to play World of Warcraft 6.3 WoD
I can move the cursor to lower parts of the screen where the actionbars are placed but clicking abilities to use them doesn't work.
It seems that the box that we can interact in is smaller then the actual game window.
I estimate the box we can interact in to be 5cm smaller than it should be

This happens  in fullscreen mode and windowed fullscreen and in windowed mode as well.
I tried to play with winecfg but so far the only thing that happens is that the window moves out of the visible screen if i do not let the windowmanager control the game window.
capture mouse cursor didn't change it either.
Virtual desktop wasn't needed either when i played it before WoD.

The only way to actually use the buttons is either resize the game window or use the keyboard shortcuts associated with the buttons.
Neither of the 2 solutions is really great, so i hope for some input on this.

**Comment by yoshimo** [comment]
mhmm i tried a few settings in winecfg and wow and still think it might be a config issue:

Config1: Virtual Desktop , 1440x900 , WoW resolution 800x600 , windowed, no issue
Config2: Virtual Desktop: 1920x1040, WoW resolution 1920x1040, windowed fullscreen, no issue
Config3: NO Virtual Desktop: 1920x1040, WoW resolution 1920x1040, windowed fullscreen-> cursor is locked to the upper part of the screen.

in all 3 cases  the window manager of Kubuntu 14:10 is allowed to control windows and decorate them.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
