### ISSUE TITLE
error during make

### ISSUE THREAD

**Issue by jzemeocala** [wine-compholio/wine-staging#199]
While trying to compile wine after applying the compholio patchset Ikeep on running into this error:

process.c: In function ‘create_process’:
process.c:2144:12: error: ‘struct new_process_request’ has no member named ‘env_size’
         req->env_size       = (env_end - env) * sizeof(WCHAR);
            ^
process.c:2145:12: error: ‘struct new_process_request’ has no member named ‘process_sd_size’
         req->process_sd_size = process_sd_size;
            ^
make[1]: *** [process.o] Error 1
make[1]: Leaving directory `/home/jzemeocala/wine-staging-3dd8fd35af98dc9cccd6cd417bf2b922b86554e1/dlls/kernel32'
make: *** [dlls/kernel32] Error 2

I can't seem to find any info about this error or how to correct it. Any help would be greatly appreciated

**Comment by slackner** [comment]
As there wasn't any activity for several months I will assume that the issue was fixed in the meantime. Feel free to reopen if this is not the case.

For the record: Our Wiki contains now much more information about building/packaging Wine:
* https://github.com/wine-compholio/wine-staging/wiki/Installation
* https://github.com/wine-compholio/wine-staging/wiki/Packaging
* https://github.com/wine-compholio/wine-staging/wiki/Development
