### ISSUE TITLE
Microsoft Word 2007 needs unimplemented function propsys.dll.PSGetPropertyDescriptionListFromString for saving a file when winver set to Vista or later *stub patch upstreamed* *msdn link*

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#205]
https://bugs.winehq.org/show_bug.cgi?id=29788

http://msdn.microsoft.com/en-us/library/windows/desktop/bb762079%28v=vs.85%29.aspx

**Comment by deri82** [comment]
Closing here. The upstream bug is still alive. There is an easy workaround for this.

**Comment by rik-shaw** [comment]
If the workaround you refer to is using winver set to XP, this isn't a workaround for all users.  In our case, we need the Windows Vista / 7 winver so that ibus keyboarding works correctly.  Other users that have suggested that keyboarding will work correctly by disabling ibus when operating under winver XP are missing the point that ibus keyboards are needed for some users!  So, there exists no workaround that I know of the be able to keyboard with ibus keyboards in Office 2007 in wine and still be able to save documents :-(
