### ISSUE TITLE
Canonicalize charset name for IMultiLanguage2_GetCharsetInfo

### ISSUE THREAD

**Issue by DarkPlayer** [wine-compholio/wine-staging#23]
RFC for "Canonicalize charset name for IMultiLanguage2_GetCharsetInfo"

|  |  | 
| ------------- | ------------- |
| **Bug**        | https://bugs.winehq.org/show_bug.cgi?id=13340 |
| **Patch 1**      | http://winehq.org/pipermail/wine-patches/2008-May/055105.html |
| **Patch 2**      | http://winehq.org/pipermail/wine-patches/2008-May/055107.html |

According to https://bugs.winehq.org/show_bug.cgi?id=13340#c11 (comment 11) there is a better way to fix this.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
