### ISSUE TITLE
Add CUDA patchset

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#231]
Patchset:
https://github.com/lexa2/wine-cuda

Still needs to be reviewed.

----------------------------

Here is a small list of things which we should work on for 1.7.34:
- [x] Find out why Unknown1_func4 crashes
- [x] Add new exports for CUDA 6.5 (if there are any)
- [x] Add implementation for nvcuvid
- [x] Add nvapi implementation to get the windows version of PhysX working
- [x] Find out why CtxDetach crashes sometimes?

**Comment by DarkPlayer** [comment]
I added the first implementation for CUDA in commit e09be4fd77559081e451da31ea390c186bc3a67d. There are still some things which should be improved till the next release, but the patch is sufficient to run all CUDA samples with one exception.  

The implementation is written against CUDA 6.0 and is backwards compatible for applications using older CUDA versions (unlike the original proposed solution), but your nvidia driver must be up-to-date to support CUDA 6.0 or higher. You should verify that cuda is working properly by using the linux version of [CUDA-Z](http://cuda-z.sourceforge.net/)  since for example Ubuntu does not load the necessary kernel modules by default.

Feel free to try it out, just make sure that you have the cuda development files installed (especially cuda.h and cudaGL.h). At the moment the code only needs a couple definitions from this files so we may be able to get rid of them to make it easier for distributions like Fedora to enable cuda support.

Here is a small list of things which we should work on:
- [ ] Find out why the simple callback sample application crashes
- [ ] Find out why Unknown1_func4 crashes
- [ ] Add new exports for CUDA 6.5 (if there are any)
- [ ] Add implementation for nvcuvid
- [ ] Add implementation for nvenc
- [ ] Add nvapi implementation to get the windows version of PhysX working

If someone is searching for a task to work on I would recommend the nvcuvid implementation. This is the gpu decoding library of nvidia which is very simple and contains just a few functions. Adding some redirect functions should be sufficient to get everything working. 

The nvenc library would be more interesting but according to [Phoronix](http://www.phoronix.com/scan.php?page=news_item&px=MTg0NTY) the support for nvenc is only available in the most current beta version of the linux driver and I am not sure how compatible the linux and window version is.

Try it out and tell me your feedback! ;-)

**Comment by i30817** [comment]
I would honestly prefer a sort of CUDA emulation in opencl to make stubborn cpu only games offload physics to AMD cards, but oh well.

**Comment by DarkPlayer** [comment]
@i30817 You can write your own version of PhysX supporting OpenCL but this is out of the scope of this project. ;-)

**Comment by DarkPlayer** [comment]
I continued working on nvapi and got the most current PhysX version working with some fluid demo. The required nvapi functions seem to be used to to identify the gpu which is controlling the active display in order to select it for the CUDA tasks. Adding stubs should be sufficient for systems with only one nvidia GPU.

![fluid](https://cloud.githubusercontent.com/assets/3102472/5598686/d933e64c-92ba-11e4-8678-f435f5ea7f5c.png)

**Comment by DarkPlayer** [comment]
If anyone of you knows links to PhysX demos it would be great if you could post them. Nvidia provides the PhysX SDK only to registered developers and for tech demos they only provide videos and not the application itself.

It would also be interesting to try an application using VisualFX. VisualFX is like PhysX part of NVIDIA GameWorks and I wouldn't be surprised if they make use of CUDA.

**Comment by titan73** [comment]
Can you tell which demos or apps you tested so far? So we can add anything that are not on the list.
Dragon Age 2 demo uses PhysX but it crash with an stack overflow.

**Comment by titan73** [comment]
Fluid sandbox http://xenorate.com/tl_files/somekram/fluidsandbox.zip.

**Comment by titan73** [comment]
There are some downloadble nvidia demos here http://www.nvidia.com/coolstuff/demos. There are few cuda demos and one that uses PhysX w.nvidia.com/coolstuff/demos#!/supersonic-sled.

**Comment by titan73** [comment]
Argh it's dx11.

**Comment by DarkPlayer** [comment]
I tried the following PhysX programs so far:

- *PhysX FluidMark*
Download from http://www.ozone3d.net/benchmarks/physx-fluidmark/
Contains some old version of PhysX but works without issues.

- *Dark Void - Benchmark*
Download from http://www.geforce.com/games-applications/pc-games/dark-void/downloads
This game/benchmark supports 3D vision and wants to use the nvapi Stereo commands no matter which error they return. The benchmark also tries to use NvAPI_D3D9_StretchRectEx but only once.
The window starts minimized in Wine after the splash screen is shown and with 640x480 as resolution. You need to go to the graphic tab and the resolution settings (translated to "decisions" in the german version) to correct this.
 For some reason the game thinks that hardware PhysX support is disabled and  restricts the number of effects. However, the game is using CUDA during the benchmark so I am pretty sure that PhysX is working.

- *JX3Benchmark*
Dowload from http://download.nvidia.com/downloads/nZone/demos/JX3BenchmarkSetup-v1.1.1.1_EN.exe
This benchmark supports CUDA and PhysX, but the PhysX test somehow freezes during the start. I don't think that this problem is directly related to my changes, maybe someone else wants to debug this.

- *Raging Rapids Ride*
Download (see Update under the video) from http://physxinfo.com/news/2522/nvidia-physx-demo-raging-rapids-ride/
This demo by NVIDIA uses d3d9 but also tries to make use of the d3d9 commands of CUDA and therefore does not work.

- *Cryostasis Demo*
Download from http://www.geforce.com/games-applications/pc-games/cryostasis-sleep-of-reason/downloads
The demo crashes with a segmentation fault during the startup and messes around with your gamma settings. You can revert this by using `xgamma -gamma 1.0`. Seems like the game never worked in wine correctly (see https://bugs.winehq.org/show_bug.cgi?id=18663).

I will push the code for nvapi later, so you can do your own experiments.

**Comment by deri82** [comment]
Cryostasis Demo according to that bug report contains dx10 code which is unimplemented. No way to get it run...

**Comment by DarkPlayer** [comment]
@deri82 You need to disable d3d10, d3d10core and the demo falls back Diredt3D9. The d3d10 libraries are only marked as delay import.

**Comment by DarkPlayer** [comment]
The nvapi stubs are now in the repository, so you can all do your own PhysX tests. Make sure to verify that CUDA works and then install PhysX from http://www.nvidia.de/object/physx-9.13.0725-driver-de.html

I think the PhysX FluidMark benchmark is good starting point for a first test. It will show whether GPU acceleration is supported and you can disable/enable the GPU (disabled by default).

**Comment by DarkPlayer** [comment]
Btw, it would be great if someone could run the nvapi crosstest on a windows system with a nvidia graphic card and post the output. Some tests are quite hard coded to my test system and maybe I can figure out the meaning of the remaining structure values this way.

**Comment by titan73** [comment]
English link to download physx http://www.nvidia.com/object/physx-9.14.0702-driver.html.

**Comment by slackner** [comment]
Have updated the todo-list in https://github.com/wine-compholio/wine-staging/issues/231#issuecomment-68503050. All remaining issues should be tested/fixed till the release of 1.7.34.

**Comment by DarkPlayer** [comment]
CUDA 6.5 contains the following new exports which needs to be added:

@ stub cuGLGetDevices_v2
@ stub cuGraphicsResourceSetMapFlags_v2
@ stub cuLinkAddData_v2
@ stub cuLinkAddFile_v2
@ stub cuLinkCreate_v2
@ stub cuMemHostRegister_v2
@ stub cuOccupancyMaxActiveBlocksPerMultiprocessor
@ stub cuOccupancyMaxPotentialBlockSize

**Comment by slackner** [comment]
CUDA 6.5 specific functions have been added in 09dbde31048425f47452e3501ba1cd421e6c5adc.

**Comment by slackner** [comment]
Both the crash in Unknown1_func4 and CtxDetach are fixed now with a proper wrapper of the "undocumented interface 4". Awesome job @DarkPlayer for figuring out how all these internal functions work. :)

Only remaining task is to figure out why `simpleCallback.exe` from the CUDA SDK crashes with a `wine client error`.

**Comment by DarkPlayer** [comment]
We reached all our goals regarding CUDA for the 1.7.34 release, so I am closing the bug report.

**Comment by titan73** [comment]
This is awesome! Great work!!!

**Comment by DJATOM** [comment]
Thanks for adding CUDA support, but I've got error in dgdecnv, so after some debugging I fixed it for me. There is not an universal cuLoadModule error fix 'cuz I'm too lazy for studying wine code and add win2posix conversion onto this function, but if it will be useful for someone, there is a patch: http://rghost.ru/69FGr4cXQ.

**Comment by slackner** [comment]
@DJATOM: Thanks for pointing out this issue. I have just added a patch which should properly translate the filenames: https://github.com/wine-compholio/wine-staging/blob/master/patches/nvcuda-CUDA_Support/0009-nvcuda-Implement-cuModuleLoad-wrapper-function.patch - does that fix it?

**Comment by DJATOM** [comment]
@slackner Yes, I rebuilt wine-staging with your patch and seems it works well. Thank you.
