### ISSUE TITLE
Cannot play movie on blinkbox.com

### ISSUE THREAD

**Issue by leighman** [wine-compholio/wine-staging#233]
I get Error 117 when trying to play a movie on blinkbox.

Please let me know how I can help debug this.

Pipelight 0.2.8 on Ubuntu 14.04 from the ppa. Silverlight 5.1. All up to date.

**Comment by compholio** [comment]
@leighman: Sorry I just noticed this, have you tried Silverlight 5.0?  Some Silverlight services require extra content protection on Silverlight 5.1 but work just fine with Silverlight 5.0.

**Comment by leighman** [comment]
I did try 5.0. Or atleast used plugin --enable silverlight-5.0 --disable silverlight-5.1

**Comment by compholio** [comment]
Odd, could you try resizing/moving your browser window and see if that causes it to render the whole window?

**Comment by slackner** [comment]
If the issue is still present please attach the output from `pipelight-plugin --system-check`.

**Comment by leighman** [comment]
>> 32 bit <<

Checking Wine version ...
Version: wine-1.7.33 (Staging)
Patched Wine version: PASSED
(Run '/usr/share/pipelight/wine --patches' for more details.)

Checking OpenGL ...
OpenGL Vendor: Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
OpenGL Direct Rendering: True
OpenGL: PASSED

Checking fonts ...
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\Arial.ttf
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\Arial_Bold.ttf
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\arialbi.ttf
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\ariali.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\Verdana.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\verdanab.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\Verdana_Bold_Italic.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\Verdana_Italic.ttf
Fonts: PASSED

Checking ACLs / XATTR ...
ACLs: PASSED

Checking libraries...
libcapi20.so.3: /usr/lib/i386-linux-gnu/libcapi20.so.3
libcups.so.2: /usr/lib/i386-linux-gnu/libcups.so.2
libdbus-1.so.3: /lib/i386-linux-gnu/libdbus-1.so.3
libfontconfig.so.1: /usr/lib/i386-linux-gnu/libfontconfig.so.1
libfreetype.so.6: /usr/lib/i386-linux-gnu/libfreetype.so.6
libGL.so.1: /usr/lib/i386-linux-gnu/mesa/libGL.so.1
libgnutls.so.26: /usr/lib/i386-linux-gnu/libgnutls.so.26
libgsm.so.1: /usr/lib/i386-linux-gnu/libgsm.so.1
libjpeg.so.8: /usr/lib/i386-linux-gnu/libjpeg.so.8
libncurses.so.5: /lib/i386-linux-gnu/libncurses.so.5
libnetapi.so: missing
libodbc.so.1: /usr/lib/i386-linux-gnu/libodbc.so.1
libpcap.so.0.8: /usr/lib/i386-linux-gnu/libpcap.so.0.8
libpng12.so.0: /lib/i386-linux-gnu/libpng12.so.0
libsane.so.1: /usr/lib/i386-linux-gnu/libsane.so.1
libtiff.so.5: /usr/lib/i386-linux-gnu/libtiff.so.5
libtxc_dxtn_s2tc.so.0: /usr/lib/i386-linux-gnu/libtxc_dxtn_s2tc.so.0
libv4l1.so.0: /usr/lib/i386-linux-gnu/libv4l1.so.0
libX11.so.6: /usr/lib/i386-linux-gnu/libX11.so.6
libXcomposite.so.1: /usr/lib/i386-linux-gnu/libXcomposite.so.1
libXcursor.so.1: /usr/lib/i386-linux-gnu/libXcursor.so.1
libXext.so.6: /usr/lib/i386-linux-gnu/libXext.so.6
libXi.so.6: /usr/lib/i386-linux-gnu/libXi.so.6
libXinerama.so.1: /usr/lib/i386-linux-gnu/libXinerama.so.1
libXrandr.so.2: /usr/lib/i386-linux-gnu/libXrandr.so.2
libXrender.so.1: /usr/lib/i386-linux-gnu/libXrender.so.1
libxslt.so.1: /usr/lib/i386-linux-gnu/libxslt.so.1
libXxf86vm.so.1: /usr/lib/i386-linux-gnu/libXxf86vm.so.1
Libraries: FAILURE

>> 64 bit <<

Checking Wine version ...
Version: wine-1.7.33 (Staging)
Patched Wine version: PASSED
(Run '/usr/share/pipelight/wine64 --patches' for more details.)

Checking OpenGL ...
OpenGL Vendor: Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL Direct Rendering: True
OpenGL: PASSED

Checking fonts ...
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\Arial.ttf
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\Arial_Bold.ttf
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\arialbi.ttf
Found Arial in Z:\usr\share\fonts\truetype\msttcorefonts\ariali.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\Verdana.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\verdanab.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\Verdana_Bold_Italic.ttf
Found Verdana in Z:\usr\share\fonts\truetype\msttcorefonts\Verdana_Italic.ttf
Fonts: PASSED

Checking ACLs / XATTR ...
ACLs: PASSED

Checking libraries...
libcapi20.so.3: /usr/lib/x86_64-linux-gnu/libcapi20.so.3
libcups.so.2: /usr/lib/x86_64-linux-gnu/libcups.so.2
libdbus-1.so.3: /lib/x86_64-linux-gnu/libdbus-1.so.3
libfontconfig.so.1: /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
libfreetype.so.6: /usr/lib/x86_64-linux-gnu/libfreetype.so.6
libGL.so.1: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
libgnutls.so.26: /usr/lib/x86_64-linux-gnu/libgnutls.so.26
libgsm.so.1: /usr/lib/x86_64-linux-gnu/libgsm.so.1
libjpeg.so.8: /usr/lib/x86_64-linux-gnu/libjpeg.so.8
libncurses.so.5: /lib/x86_64-linux-gnu/libncurses.so.5
libnetapi.so: missing
libodbc.so.1: /usr/lib/x86_64-linux-gnu/libodbc.so.1
libpcap.so.0.8: /usr/lib/x86_64-linux-gnu/libpcap.so.0.8
libpng12.so.0: /lib/x86_64-linux-gnu/libpng12.so.0
libsane.so.1: /usr/lib/x86_64-linux-gnu/libsane.so.1
libtiff.so.5: /usr/lib/x86_64-linux-gnu/libtiff.so.5
libtxc_dxtn_s2tc.so.0: /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0
libv4l1.so.0: /usr/lib/x86_64-linux-gnu/libv4l1.so.0
libX11.so.6: /usr/lib/x86_64-linux-gnu/libX11.so.6
libXcomposite.so.1: /usr/lib/x86_64-linux-gnu/libXcomposite.so.1
libXcursor.so.1: /usr/lib/x86_64-linux-gnu/libXcursor.so.1
libXext.so.6: /usr/lib/x86_64-linux-gnu/libXext.so.6
libXi.so.6: /usr/lib/x86_64-linux-gnu/libXi.so.6
libXinerama.so.1: /usr/lib/x86_64-linux-gnu/libXinerama.so.1
libXrandr.so.2: /usr/lib/x86_64-linux-gnu/libXrandr.so.2
libXrender.so.1: /usr/lib/x86_64-linux-gnu/libXrender.so.1
libxslt.so.1: /usr/lib/x86_64-linux-gnu/libxslt.so.1
libXxf86vm.so.1: /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1
Libraries: FAILURE

**Comment by deri82** [comment]
Any update on this?

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
