### ISSUE TITLE
Tera Online Seems to Freeze

### ISSUE THREAD

**Issue by eliwap** [wine-compholio/wine-staging#240]
I have originally opened a ticket at https://bugs.winehq.org/show_bug.cgi?id=37725 before realizing I should have opened this here at wine stagging. I am pasting below my findings todate as posted in the original bug report. I will adding the asked for info regarding my configuration settings in additional posts.

I'm beginning to feel that I've stepped way outta my league here. I dunno how to investigate this further, so I will just report my observations and hopefully we will be able to work this out together.

First off I am running:

Fedora 21 x86_64 - I will be cross referencing this with wine-stagging
wine 1.7.33 i686 there are no x86_64 wine libraries
KDE 4.14.3
8GB RAM
I7
NVIDIA 650 GTX w/ 2GB RAM

As you are probably aware, KDE comes with build in desktop effects dependant on opengl (of course). Before running the game, I have been in the habit of disabling the desktop effects by pressing on [CTL][SHFT][F11]. Then I would run the launcher. With wine 1.7.30, everything went well. Fedora skipped over building 1.7.31 so I did not have the opportunity to try it. But with 1.7.32 and 1.7.33 the main game screen would start, but then the game would seem to freeze. I could not switch to anything other than switch to a console and kill the game processes.

I just wanted to test things to see if I could get it to run, and by accident, I discovered a work around.

I can start the game when I have the desktop effects enabled. I can then go to windowed mode by pressing on [ALT][ENT]. I can then switch off the desktop effects and bring the game back to full screen mode. The game then works fine.

I hope we can figure this one out.

**Comment by eliwap** [comment]
Problem persists with wine-stagging 1.7.34

**Comment by eliwap** [comment]
Problem persists with 1.7.36 wine-stagging

**Comment by DarkPlayer** [comment]
Does the problem still exist?

**Comment by eliwap** [comment]
I will let you know

**Comment by eliwap** [comment]
Yep... the problem is still there

**Comment by deri82** [comment]
Have you tried this later with newer wine? I made a patch for this that should silence the repeated NtSetTimerResolution message.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
