### ISSUE TITLE
League of Legends often freeze with CMST enabled

### ISSUE THREAD

**Issue by alex-6** [wine-compholio/wine-staging#248]
Everytime a spell animation is triggered, the game totally freeze for beetweem 5 and 10 seconds.
The terminal logs don't show any new message when it happens.
This bug seems to produce only with CMST enabled.

I didn't find anything here to upload a logfile...So here is the log : 
https://bpaste.net/show/6431f8f0a4b0

League Of Legends 4.21 (Free Game) : https://signup.leagueoflegends.com/en/signup/redownload

WINEPREFIX components : Adobe Air, flash player, MSXML 4.0 and 6.0, vcrun2005 and 2008, IE8

wine-staging 1.7.33
nvidia 343.36
Gentoo 64, Kernel 3.14.14

**Comment by titan73** [comment]
If it works with CSMT disabled that may be good to have a log too.

**Comment by alex-6** [comment]
Sure : https://bpaste.net/show/d83303652c44

Doesn't look so different :/

**Comment by DarkPlayer** [comment]
@stefand Are you aware of this issue?

**Comment by stefand** [comment]
Am 2015-01-07 um 19:00 schrieb Michael Müller:
> @stefand <https://github.com/stefand> Are you aware of this issue?
Nope. I'll try to fix some of the focus regressions before dealing with
more CSMT problems though

**Comment by jacobmischka** [comment]
Is there any word on this? I get almost double fps with CSMT than with OpenGL, if these freezes didn't happen it would be perfect. If there's any way I can help I'll be happy to try.

**Comment by alex-6** [comment]
These freeze happens with default options of the game.cfg file (the game config file, note wine config file).
Anyway, I don't have this freeze anymore with "x3d_platform=1" option (which is supposed to use openGL I guess)

In all case with any config, the game is alway laggy when there start to be some teamfights (for example 10 champions throwing spells with effects and animations)...

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
