### ISSUE TITLE
Dragon Age Origins crash with graphic bug when changing Anti-aliasing settings

### ISSUE THREAD

**Issue by alex-6** [wine-compholio/wine-staging#249]
When changing the anti-aliasing settings from 4x to 16x, the game crash with random colors everywhere on the screen. This only happens with CMST enabled.

wine-staging 1.7.33
nvidia 343.36
Gentoo 64, Kernel 3.14.14

There are 117MB of logs like that (with the number after drawprim.c changing to 77 sometimes).

"fixme:d3d:context_check_fbo_status FBO status GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT (0x8cd6)
fixme:d3d:context_check_fbo_status 	Location WINED3D_LOCATION_RB_MULTISAMPLE (0x100).
fixme:d3d:context_check_fbo_status 	Color attachment 0: (0x1ca330) WINED3DFMT_B8G8R8A8_UNORM 1920x1080 16 samples.
fixme:d3d:context_check_fbo_status 	Depth attachment: (0x1d75d0) WINED3DFMT_D24_UNORM_S8_UINT 1920x1080 16 samples.
err:d3d:wined3d_debug_callback 0xc14dbf0: "GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.".
err:d3d_draw:draw_strided_fast >>>>>>>>>>>>>>>>> GL_INVALID_FRAMEBUFFER_OPERATION (0x506) from glDrawArrays @ /var/tmp/notmpfs/portage/app-emulation/wine-1.7.33-r4/work/wine-1.7.33/dlls/wined3d-csmt/../wined3d/drawprim.c / 89
fixme:msvcrt:__clean_type_info_names_internal (0xe91f14) stub
fixme:msvcrt:__clean_type_info_names_internal (0x100424c4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x3e87dc) stub"

Errors concerning context.c 

"err:d3d_surface:wined3d_surface_load_location Don't know how to handle location 0x100.
err:d3d_surface:wined3d_surface_load_location Don't know how to handle location 0x100.
err:d3d:wined3d_debug_callback 0xf1ac770: "GL_OUT_OF_MEMORY error generated. Failed to allocate memory for texture.".
err:d3d:context_attach_depth_stencil_rb >>>>>>>>>>>>>>>>> GL_OUT_OF_MEMORY (0x505) from glFramebufferRenderbuffer() @ /var/tmp/notmpfs/portage/app-emulation/wine-1.7.33-r4/work/wine-1.7.33/dlls/wined3d-csmt/../wined3d/context.c / 111"

Errors concerning device.c

fixme:d3d:context_check_fbo_status FBO status GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT (0x8cd6)
fixme:d3d:context_check_fbo_status 	Location WINED3D_LOCATION_RB_MULTISAMPLE (0x100).
fixme:d3d:context_check_fbo_status 	Color attachment 0: (0x1ca330) WINED3DFMT_B8G8R8A8_UNORM 1920x1080 16 samples.
fixme:d3d:context_check_fbo_status 	Depth attachment: (0x1d75d0) WINED3DFMT_D24_UNORM_S8_UINT 1920x1080 16 samples.
err:d3d:wined3d_debug_callback 0xf1ac770: "GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.".
err:d3d:device_clear_render_targets >>>>>>>>>>>>>>>>> GL_INVALID_FRAMEBUFFER_OPERATION (0x506) from glClear @ /var/tmp/notmpfs/portage/app-emulation/wine-1.7.33-r4/work/wine-1.7.33/dlls/wined3d-csmt/../wined3d/device.c / 461

**Comment by DarkPlayer** [comment]
Seems like you are running out of GPU memory (GL_OUT_OF_MEMORY), but maybe @stefand knows better.

**Comment by deri82** [comment]
I have seen that so many times at winehq that I have been thinking that there is memory leak somewhere at wine source.

I searched some duplicate/similar issues. 

Warframe: Assert in OutOfMemory() crash
https://bugs.winehq.org/show_bug.cgi?id=33491

GL_OUT_OF_MEMORY: shared video memory locked arbitrarily
https://bugs.winehq.org/show_bug.cgi?id=25240

Bioshock 2 runs out of GL memory quickly
https://bugs.winehq.org/show_bug.cgi?id=34658

Crusader Kings 2 crashes after small whille with GL_OUT_OF_MEMORY
https://bugs.winehq.org/show_bug.cgi?id=29972

Dragon age 2 crashes with GL_OUT_OF_MEMORY errors
https://bugs.winehq.org/show_bug.cgi?id=32050

Workaround I have seen to be working sometimes is lowering the texture details/resolution/settings. Or setting the videomemorysize of gpu card correctly at the wine registery. For some cards it's detected wrong.

**Comment by alex-6** [comment]
Actually I realized this bug happend also with CMST disabled...

**Comment by deri82** [comment]
wine 1.7.45 fixed a bug related to this
38654  Multiple games have rendering issues when anti-aliasing enabled (King's Bounty series, GTA: San Andreas, Tomb Raider: Anniversary)

https://bugs.winehq.org/show_bug.cgi?id=38654

But if the real issue is running out of memory, that fix cant really help here.

It could be fruitful to watch this bug thread
https://bugs.wine-staging.com/show_bug.cgi?id=335

wine-staging added a feature to more accurately follow the memory usage of gpu cards. This works only for nvidia for now.  

More info here

https://bugs.wine-staging.com/show_bug.cgi?id=311

**Comment by kernelOfTruth** [comment]
It seems that it in fact is running out of memory

I remember having seen similar error messages with Dragon Age 2 and setting the graphics options to lower quality tends to prevent it - or at least delay it by a great deal (several hours or never compared to being triggered after several minutes or hours)

In the end almost the entire screen is covered in black (empty ?) textures, I've tried out several rendering targets & options but they didn't made a big difference.

Upon next opportunity I'll see how things changed

Thanks :+1:

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
