### ISSUE TITLE
Add IDirectPlayVoiceClient_GetCompressionTypes implementation

### ISSUE THREAD

**Issue by slackner** [wine-compholio/wine-staging#251]
2 patches by Alex Henrie: http://ix.io/fES
(extracted from https://github.com/alexhenrie/wine/commits/master )

@compholio / @DarkPlayer: could someone of you please run the tests in patch 1/2 in a real Windows environment? On the Wine testbot dpvoice is not present.

**Comment by DarkPlayer** [comment]
The crosstest does not compile for me:

```
../../../../../projects/wine/dlls/dpvoice/tests/voice.c: In function ‘test_client_GetCompressionTypes’:
../../../../../projects/wine/dlls/dpvoice/tests/voice.c:387:5: error: initializer element is not constant
     static const int info_table_size = num_types * sizeof(DVCOMPRESSIONINFO);
     ^
make: *** [voice.cross.o] Fehler 1
```

**Comment by compholio** [comment]
The machine I have for testing is Win7, I don't think I can use dplayvoice on it.

**Comment by DarkPlayer** [comment]
The test from https://github.com/alexhenrie/wine/commit/7fbd6363e856b859b625f2ae814936e558b9217d passes now.

**Comment by alexhenrie** [comment]
I've since made a few small corrections to the tests, but they should still pass for you.

**Comment by alexhenrie** [comment]
I'm actually not sure that I should be testing those strings at all, since they vary from one language to the next.

**Comment by DarkPlayer** [comment]
One test on a chinese Windows btw. returned the same strings as on an english system.

**Comment by DarkPlayer** [comment]
@alexhenrie Your tests are essentially useless on Wine.

You only execute the compression tests when both, the server and client could be initialized:
```c
if(test_init_dpvoice_server() && test_init_dpvoice_client())
{
    test_GetCompressionTypes((void*)vclient->lpVtbl->GetCompressionTypes, vclient, "client");
    test_GetCompressionTypes((void*)vserver->lpVtbl->GetCompressionTypes, vserver, "server");
}
``` 

However, the client is only considered as initialized if the expression `return vclient != NULL;` evaluates to TRUE, but the function to initialize the vclient is marked as todo_wine:

```c
hr = IDirectPlayVoiceClient_Initialize(vclient, (IUnknown*)dpclient, DirectPlayVoiceClientMessageHandler, NULL, 0, 0 );
todo_wine ok(hr == S_OK, "Connect failed with 0x%08x\n", hr);
```

This causes `test_init_dpvoice_client()` to return FALSE and none of the tests is executed. You should at least use something like the following code to ensure that the server tests get executed.
```c
if (test_init_dpvoice_server())
    test_GetCompressionTypes((void*)vserver->lpVtbl->GetCompressionTypes, vserver, "server");
if (test_init_dpvoice_client())
    test_GetCompressionTypes((void*)vclient->lpVtbl->GetCompressionTypes, vclient, "client");
```

It also wouldn't hurt to print a skip message in the else case to inform the user that not all tests were executed.

There are also some other possible improvements. I created a todo so that I can check the checkbox after you solved one of the problems.
- [ ] Execute at least dpvoice server tests in Wine
- [ ] First copy the DVCOMPRESSIONINFO types and then modify the lpszName in the duplicated data
- [ ] Do not use hard coded string offsets, but compute them at runtime (i.e. strlenW)

**Comment by slackner** [comment]
Since the patch still contains a couple of flaws (main issue is that tests do not run properly) deferring to the next release.

**Comment by alexhenrie** [comment]
I fixed up the tests so that the server tests will run even if the client cannot be initialized.

What we really need to do is put the strings in a resource file. This would remove the need for hardcoded string offsets, plus it would make these strings properly localizable via Wine's .po files. Using string resources is also what Windows does, but Windows has them in inconsistent formats and scattered across 6 files, only one of which (msacm32.dll) is currently included in Wine:

```
dpvvox.dll:
  STRING Name=0001 Language=0409:
    0001 "Voxware SC03 3.2kbit/s"
    0003 "Voxware SC06 6.4kbit/s"
    0005 "Voxware VR12 1.4kbit/s"

msacm32.dll:
  STRING Name=0001 Language=0409:
    0000 "MS-PCM"

msadp32.acm:
  STRING Name=0001 Language=0409:
    0001 "MS-ADPCM"

msgsm32.acm:
  STRING Name=0001 Language=0409:
    0001 "Microsoft GSM 6.10"

tssoft32.acm:
  STRING Name=0001 Language=0409:
    0001 "TrueSpeech(TM)"

dpvacm.dll:
  STRING Name=0001 Language=0409:
    0001 "%s %s"
    0002 "%d kbit/s"
    0003 "%d.%d kbit/s"
```

So the question is: Should we add stubs for the remaining 5 files, so that we can put the resources where they belong and duplicate the Windows behavior as closely as possible? Or should we simply add a resource file to dpvoice.dll that contains the 7 strings we need? And if I do create a resource file for dpvoice.dll, should I use the numbers 1-7 for the resource IDs, or something else?

**Comment by slackner** [comment]
Sorry for the delayed answer, I somehow missed your answer. I would prefer adding the resources directly to dpvoice.dll. This can be changed later again, as soon as we actually are planning to implement some of these codecs - but in the meantime it doesn't make much sense, and might cause some applications to call unimplemented functions.

Usually you do not directly numbers as resource IDs, but instead define them in a header file. Take a look at existing dlls/programs which use resources.

programs/regedit/resource.h:
```
#define ID_REGISTRY_MENU                0
#define ID_EDIT_MENU                    1
#define ID_VIEW_MENU                    2
#define ID_FAVORITES_MENU               3
#define ID_HELP_MENU                    4
#define ID_EDIT_NEW_MENU                5
```

programs/regedit/regedit.rc:
```
#include "resource.h"

#pragma makedep po

LANGUAGE LANG_ENGLISH, SUBLANG_DEFAULT

[...]

STRINGTABLE
BEGIN
    ID_REGISTRY_MENU        "Contains commands for working with the whole registry"
    ID_EDIT_MENU            "Contains commands for editing values or keys"
    ID_VIEW_MENU            "Contains commands for customizing the registry window"
    ID_FAVORITES_MENU       "Contains commands for accessing frequently used keys"
    ID_HELP_MENU            "Contains commands for displaying help and information about registry editor"
    ID_EDIT_NEW_MENU        "Contains commands for creating new keys or values"
END
```

By using definitions it doesn't really matter how the IDs are exactly defined, and you can also change that at any time later.

**Comment by DarkPlayer** [comment]
I think you should find out whether these supported codec dlls are hard coded into dpvoice or whether they are somehow registered, for example through some registry key. Maybe there are also registry keys containing the name of the codecs.

If the codecs are for example added to the registry when calling DllRegisterServer on these dlls, it might be a good idea to mime this behavior so that you can enable/disable these codecs simply by disabling the library. This might might also allow to use native dlls for the actual (de)compression in the future.

**Comment by alexhenrie** [comment]
@DarkPlayer I can't find the codec names or GUIDs in the registry. They appear to be hardcoded in dpvoice.dll.
@slackner Won't Alexandre object to adding resources to dpvoice.dll that aren't in the original?

**Comment by alexhenrie** [comment]
@slackner Or can we just say that this hardcoded implementation is good enough for now?

**Comment by slackner** [comment]
hardcoded is good enough, at least for wine-staging. not sure about upstream wine though

**Comment by alexhenrie** [comment]
@slackner Is Alexandre more likely to accept a hardcoded solution or a string resources solution?

**Comment by slackner** [comment]
I am not really sure, if AJ accepts at all returning a list of codecs, where basically not a single one is implemented. ;) He might want that the returned list actually matches what is supported, and that the enumeration of supported codecs is similar to how it works on Windows. I am not sure if it is hardcoded on Windows, which might need some more investigation - for example, what happens if one of those DLLs does not exist. Does the corresponding codec then disappear from the list?

**Comment by alexhenrie** [comment]
Some quick tests revealed the following:
* Remove dpvvox.dll or msacm32.dll and the DLL is reinstalled automatically.
* Remove dpvacm.dll and the tests crash.
* Remove msadp32.acm or msgsm32.acm and the corresponding compression type disappears from dpvoice's compression type list.

**Comment by alexhenrie** [comment]
Really all I need is for GetCompressionTypes to return one valid name and GUID. So what if I wrote a smaller patch that just puts MS-PCM in the list? Would that be likely to be accepted, because Wine already implements msacm32.dll?

**Comment by slackner** [comment]
Yes, I think that will more likely be accepted by upstream wine.

**Comment by alexhenrie** [comment]
OK. Let's try to write a simple patch that fixes https://bugs.winehq.org/show_bug.cgi?id=29238 but is general enough that a more generic implementation can be built on top of it later. I've rewritten my master branch to only put MS-PCM in the list, and moved the more general dpvoice work to https://github.com/alexhenrie/wine/commits/dpvoice-all-compression-types

Since this new patch is just designed to be a semi-stub, and writing tests that will pass on both Windows and an incomplete Wine implementation is very difficult, do you think Alexandre will accept the patch without tests?

**Comment by slackner** [comment]
No, you will still need tests, but you can write them much more general with the knowledge that the list might be different.

I would suggest to do the test like:
* first of all, test with invalid arguments
* then use a very big buffer, so that the function suceeds - calculate the required length based on the returned string
* test that the string are really copied (pointers point into the provided buffer)
* try again with required_length - 1, it should fail now

that should be sufficient

**Comment by slackner** [comment]
Added in 372c004139e278eafa3712cbcc5f94250c213c22.
