### ISSUE TITLE
Dragon Age Origins crash in some areas of the game

### ISSUE THREAD

**Issue by alex-6** [wine-compholio/wine-staging#262]
With both CMST enabled and disabled, Dragon Age Origins crashes in some areas of the game (here, Denerim)

Here is the log + backtrace : https://bpaste.net/show/2d7a4cc0d86f

It seems to be a bug related to missing texture on characters also affecting normal wine leading to that : 

https://bugs.winehq.org/show_bug.cgi?id=33362

wine-staging 1.7.33
nvidia 343.36
Gentoo 64, Kernel 3.14.14

Tell me if you need more specific logs / informations

**Comment by alex-6** [comment]
It really seems to be related to texture detail level.
Lowering this option removes the bug with textures replaced by black.But anyway sometimes it still crash, but rarely.
I've red similar bugs are also happening on windows so I can't be 100% sure it's a wine bug...

**Comment by deri82** [comment]
The log has vanished. Would you mind trying this with more recent wine-staging?

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
