### ISSUE TITLE
add patch xlive is god idea 

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#268]
Add patch for games requeriments xlive is patch is works
https://github.com/Seegras/wine

**Comment by Eignar17** [comment]
@slackner @compholio @titan73 @DarkPlayer is add patch in To project ?

**Comment by DarkPlayer** [comment]
I just scrolled through the implementation of xlive (i.e this [files](https://github.com/Seegras/wine/tree/work/dlls/xlive)). Some stuff could be simplified, for example all the socket functions could directly be relayed inside of the spec file instead of manually relaying them.

Nevertheless, I am wondering why you are not simply using the native xlive.dll? I could only find only one [bug report](https://bugs.winehq.org/show_bug.cgi?id=36628) about using the native xlive.dll in Wine. The main problem seems to be the missing named pipe message mode support which is fixed in Wine Staging. There still seems to be another problem, but it looks more reasonable to hunt down the remaining issues instead of reinventing the wheel.

Maybe someone else knows better than me and there is a fundamental issue in Wine why xlive.dll can not work, so feel free to correct me in this case.

**Comment by Eignar17** [comment]
I see this part of the error is and the best way is to have it implemented also is just 1 dll is not much work you just have to adjust to getting it right and have a better wine

**Comment by Eignar17** [comment]
Sorry my bat English

**Comment by deri82** [comment]
Upstream has few open bugs related to this. 

Multiple games need xlive.dll implementation (Fallout 3, Batman, GTA IV) 
https://bugs.winehq.org/show_bug.cgi?id=23532

Multiple GFWL (Games For Windows Live) 2.0.0687.0 games fail on startup, reporting 'E_INVALIDARG : XLiveInitialize(&xii)' (Resident Evil 5) 
https://bugs.winehq.org/show_bug.cgi?id=36628

Multiple GFWL (Games For Windows Live) 3.5 games crash on startup due to incomplete Windows LiveID install (Street Fighter X Tekken) 
https://bugs.winehq.org/show_bug.cgi?id=31744

Multiple GFWL (Games For Windows Live) 1.x games crash on startup (Kane & Lynch: Dead Men) 
https://bugs.winehq.org/show_bug.cgi?id=28768

and few others that mention xlive

**Comment by slackner** [comment]
I am not really sure who originally wrote these patches, but I assume it is @tizbac?

I would happily accept implementations for xlive (and also for some other components which are frequently suggested by our users) for our Wine-Staging tree, but just grabbing arbitrary large patches from other repos is never a good idea. For small patchsets it is possible to add them after carefully reviewing, but for big patchsets we would always like to have some cooperation with the authors.

Only when the author is still improving it / willing to fix bugs / can provide properly rebased and formatted patches it makes sense to add it. Sometimes we also spot obvious errors in the implementation, and in such a situation we would like to have those fixed first. Whereas PlayOnLinux would probably just take any patchset as-is, without further reviewing, we always try to make sure that it is correct. That is also what a lot of people like about wine-staging, and why we are the default wine version in some distributions - I don't really think we want to change our guidelines here. ;)

@DarkPlayer: I agree that adding an implementation for new dlls is always a bit risky, but there are a lot of ways to solve that. Preferring the native DLL if it exists, disabling it by default, adding a warning in the terminal output, ...

**Comment by Eignar17** [comment]
@tizbac add your patch in wine-staging

**Comment by tizbac** [comment]
I'm not entirely sure atm about it's legal side, it would be legal only in the EU i guess, because in the USA both reverse engineering by dissassemble and eluding software protections ( which xlive falls into i think ) is illegal

**Comment by tizbac** [comment]
Also, even if native xlive would work with wine, it's better having a built-in version that provides basic functionality like there's for other libraries
The wine version is still missing multiplayer support ( lan) because of lack of "intel" , but at least it allows to save and load games

**Comment by Eignar17** [comment]
@slackner @compholio @titan73 @DarkPlayer is add patch?

**Comment by DarkPlayer** [comment]
No we can't add the patches by @tizbac since he violated the Wine rules by disassembling windows binaries. I my opinion this bug should be closed, any other opinions @slackner @compholio?

**Comment by slackner** [comment]
I agree, we can't include such patches in our Staging version for legal reasons. People from locations where the reverse engineering laws allow it can still apply the patch on their own though.

**Comment by tizbac** [comment]
It could be added when Microsoft releases public docs for the xlive API
Il 31/gen/2015 05:59 "slackner" <notifications@github.com> ha scritto:

**Comment by DarkPlayer** [comment]
Even if microsoft would release the header file, the patch would need to be rewritten by someone else. If you disassembled a microsoft library, you lost the permission to send in patches for (at least) this library according to the Wine rules.

**Comment by tizbac** [comment]
I've disassembled games to figure out what they expect from the library to
be more precise, and used some docs available from xbox sdk

2015-01-31 15:52 GMT+01:00 Michael Müller <notifications@github.com>:

**Comment by deri82** [comment]
Would xbox sdk give any benefit for wine project?

**Comment by tizbac** [comment]
Some of the functions are common between xbox and windows xlive, but some
are not and have been obtained with heavy reverse engineering of games such
as resident evil 5 , tron evolution

2015-01-31 18:31 GMT+01:00 deri82 <notifications@github.com>:
