### ISSUE TITLE
Let window managers group all Wine programs together.

### ISSUE THREAD

**Issue by matkarlg** [wine-compholio/wine-staging#269]
Issuing this command:
`xprop | grep WM_CLASS`

Using upstream Wine reveals:
> WM_CLASS(STRING) = "program_name.exe", "Wine"

Wine-staging:
> WM_CLASS(STRING) = "program_name.exe", "program_name.exe"

You can no longer match Wine programs using the classname. This can for example, be a problem for tiled WMs where you might want to impose special resizing or positioning for all Wine programs.

This might be the patch that changed the behavior:
[Prevent-window-managers-from-grouping-all-wi.patch](https://github.com/wine-compholio/wine-staging/blob/master/patches/winex11-Window_Groups/0001-winex11-Prevent-window-managers-from-grouping-all-wi.patch)

Isn't the upstream behavior more desirable as it seems wine-staging is just removing a feature?

Thank you.

**Comment by DarkPlayer** [comment]
The intended behavior is to group windows which belong to each other, i.e multiple notepad instances. 

The patch was added as many users were complaining about Gnome and Unity grouping all their running Wine programs together. There is also a upstream bug for this problem: https://bugs.winehq.org/show_bug.cgi?id=32699

The aim of Wine is to seamlessly integrate into the system: creating desktop files, assigning mime types, etc. You can argue whether you want this kind of integration, but the changed solution is the more correct one from Wine's point of view. The Windows API provides some additional functions to control the grouping of windows which are not yet implemented, but the current approach is already close to the correct solution.

**Comment by slackner** [comment]
I have to agree with @DarkPlayer, all reguar Linux programs also use the application name as WM_CLASS and not for example the toolkit which was used for development. Since Wine has the goal to integrate Windows applications seamless into the rest of the Unix environment, it makes more sense to return an application specific name here, with the big advantage that Gnome/Unity stops grouping them all together.

Is there any particular use-case for adding a rule which matches all Wine programs? If it is possible to match via regular expression we might also be able to tweak that patch a bit, so that WM_CLASS starts with the same prefix for all wine applications.

**Comment by LoathingKernel** [comment]
I believe that the proposed solution of adding a prefix is a good compromise. I can see the reasoning behind the patch but it breaks most tilling window managers. 

In my case, the common WM_CLASS allows me to add a rule in awesomewm, set all Wine windows into floating mode. This prevents the WM from trying to impose its size and position preference, which preference can result in flickering windows, games refusing to use the full screen or windows larger/smaller than the content.

**Comment by slackner** [comment]
@LoathingKernel: `winecfg` also has several checkboxes in the graphics tab to configure the behaviour of window managers (allow to decorate the windows, allow to control the windows, ...) - do these options have a similar effect, or is it really necessary to add WM preferences to prevent games from flickering?

**Comment by LoathingKernel** [comment]
If I uncheck the "Allow window manager to control the windows" checkbox, the WM stops controlling the windows, which fixes the issue, but at the same time, they also skip the taskbar and they create icons of the minimized windows at the bottom, which is not pretty nor seamless.

**Comment by QuLogic** [comment]
`xprop | grep '^_'` shows many custom properties, so how about adding one for Wine programs? Then `WM_CLASS` can continue to be used in a manner that works consistently with native programs, and there's no need to add new options.

**Comment by LoathingKernel** [comment]
This will require either the WM supporting that custom property or allowing you to specify it in order to match it. As a workaround, for now I have matched ``*.exe`` in ``WM_CLASS``, which will work until the class has the suffix ``exe`` in it.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
