### ISSUE TITLE
Please add MacOS binary builds of wine-staging for testing! 

### ISSUE THREAD

**Issue by oscarbg** [wine-compholio/wine-staging#272]
Would be nice to see if we can run GPU PhysX demos on MacOS with these CUDA enabled Wine!

**Comment by compholio** [comment]
@slackner, @DarkPlayer: we talked about this before, do you want me to talk to my wife about using her old mac for builds?

**Comment by oscarbg** [comment]
don't know if this is a serious question or a joke? can't you get hackintosh on a partition working? I have a Maxwell GPU (GTX 970) with Yosemite on my PC with CUDA 6.5 and all working (CUDA-Z, CUDA SDK samples work!).. I might be interested in at least doing some personal builds (can publish somewhere publicily) if you point me or post some tutorial on how to build wine-staging for Mac..

**Comment by slackner** [comment]
Hi,

this ideas was serious. One of the biggest problems we have with providing MacOS builds is that we can't use the same method we use for all our other distributions. We use virtual machines for all our builds - but the licenses for MacOS (except for some special versions) do not allow to do that. I don't know all the details, but @compholio and @DarkPlayer already looked into this. Thats why setting up a dedicated machine for MacOS builds might be one of the easiest solutions.

We also have to admit that we do not really have any experienced MacOS guys in our team yet, especially for creating proper packages. I guess it would not be that difficult, but if you (or someone else) could help us with that, it would definitely speed up the whole process.

Instructions for packaging (mainly the differences between regular wine and wine-staging) are documented on our wiki, see:
https://github.com/wine-compholio/wine-staging/wiki/Packaging

One of the easiest solution might be to start with packaging regular Wine, and then just add a couple of lines to apply the patches before the compile step.

Regards,
Sebastian

**Comment by DarkPlayer** [comment]
We are building 40 packages every two weeks to keep our supported distributions up-to-date and this is already a time consuming task. Everything that can not be integrated into our current build systems will require extra work. If you decide to do something like this, you at least want to have a fully functional and stable system and Hackintoshs are not very stable and may break on every update. Moreover they are not legal, so no this was a serious question.

**Comment by oscarbg** [comment]
Will try to package a Mac build soon.. will report results..
also one other idea, as I'm only interested on patches relating to nvcuda,nvapi,nvcuvid library wrappers may be possible to compile this wrappers only for Mac and "put them" on a wine prefix of other Mac Wine distros like WineSkin, Winebottler or PlayonMac?
some help, ideas for pursuing this path? thanks..

**Comment by slackner** [comment]
Hi @oscarbg,

I am not aware of any reliable method to only do a partial compile of Wine. Reusing precompiled files from other distributions will also not work because MacOS uses a completely different file format for shared libraries than Linux/BSD.

If you have trouble with compiling Wine-Staging on MacOS just ask, we might be able to help you with that. Also feel free to ask in #wine-staging on IRC freenode, where we can answer quick questions even faster than in this bugtracker.

I have just contacted the author of WineBottler and have asked him for some cooperation, if he likes the idea he might probably be able to help us with providing packages.

One additional note about CUDA on MacOS: As far as I know some functions of nvcuvid are not available on MacOS, which might have the effect that our wrapper will refuse to load. If that is really a problem we will have to use different methods for wrapping those functions. Just open a new bugreport containing the terminal output on MacOS, and we will take a closer look.

Regards,
Sebastian

**Comment by DarkPlayer** [comment]
We still don't provide any mac os x builds on our own, but play on mac and wineskin (soon) provide builds for wine staging. However, some features won't work simply because they try to load a library with ".so" extension or some other similar issues. If someone wants to fix these problems, we surely accept patches for this.

**Comment by deri82** [comment]
Isnt there mac builds now?

**Comment by DarkPlayer** [comment]
Yes, we provide builds for OS X now.
