### ISSUE TITLE
Unimplemented stubs in Dragon Age: Origins

### ISSUE THREAD

**Issue by felixonmars** [wine-compholio/wine-staging#274]
```
fixme:nvapi:unimplemented_stub function 0xd44d3c4e is unimplemented!
fixme:nvapi:unimplemented_stub function 0x6c2d048c is unimplemented!
fixme:nvapi:unimplemented_stub function 0xddf5643c is unimplemented! 
```

Full logs:
https://paste.xinu.at/rcv/

**Comment by DarkPlayer** [comment]
0xd44d3c4e -> unknown
0x6c2d048c -> NvAPI_GetErrorMessage
0x0xddf5643c -> unknown

**Comment by DarkPlayer** [comment]
Hmm, I am not sure whether it makes sense to fix these unimplemented functions at the moment. I am unable to find any information about `0xd44d3c4e` or `0xddf5643c`. 

At least `0xd44d3c4e` expects some buffer structure and passing an empty buffer makes it crash. The NvAPI_GetErrorMessage function is only called because `0xd44d3c4e` fails.

If the game works with these stubs, I think we should first concentrate on other things.

**Comment by felixonmars** [comment]
The game works fine, just doesn't use the nvcuda routine after the logs. From some searches I think the game could make use of PhysX if this were fixed somehow.

**Comment by slackner** [comment]
@felixonmars: In the following german forum post http://extreme.pcgameshardware.de/rollenspiele-und-adventures/358265-dragon-age-origins-origin-physx-cpu-screen.html there is also a bit confusion if Dragon Age Origins supports PhysX GPU support on Windows. Most users say its not possible, but there is also the following comment:

In one of the first posts one of the users claims that its possible to activate it by modifying a file `XComEngine.ini` or `Engine.ini` (somewhere located in My Documents, there are probably multiple ones), and changing `bDisablePhysXHardwareSupport` to false.

Does the game have such a file? And if yes, does it have any effect?

**Comment by titan73** [comment]
DAO from Steam installs PhysX but I don't see any related keyword in config files (./data/DAOriginsConfig.xml for example).

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
