### ISSUE TITLE
Unimplemented stub in The Elder Scrolls V: Skyrim

### ISSUE THREAD

**Issue by felixonmars** [wine-compholio/wine-staging#275]
Note that the game doesn't use PhysX, and I am not sure if the failures actually stop the game from making use of more nvapi/nvcuda functionalities.

```
fixme:nvapi:unimplemented_stub function 0xa064bdfc is unimplemented!
```

Full logs:
https://paste.xinu.at/kn9h9/

**Comment by DarkPlayer** [comment]
`0xa064bdfc -> NvAPI_D3D9_RegisterResource`
The application maybe tries to use one of the extended direct3d commands provided by nvapi.

**Comment by felixonmars** [comment]
Just for the record, currently enabling nvapi will cause visual flickering on lights and shadows in-game. The game only calls NvAPI_D3D_GetCurrentSLIState quite a lot of times during the flickering.

**Comment by DarkPlayer** [comment]
`NvAPI_D3D9_RegisterResource` was added in 93764fd3d417f837cf2a111e0d4aab23f7ce7d5f.

**Comment by DarkPlayer** [comment]
`NvAPI_D3D9_RegisterResource` stub is now added in 60d18d461028464e323ddc185ee1b3273086ca6f ;-)

**Comment by deri82** [comment]
The external log is dead. Is this still valid bug?

**Comment by felixonmars** [comment]
I think so. The unimplemented stub still causes extreme flickering in game (just tested with 1.7.42-staging).

**Comment by slackner** [comment]
It sounds like this is the same issue as in https://bugs.wine-staging.com/show_bug.cgi?id=193, is that correct?

**Comment by felixonmars** [comment]
Yes exactly.

**Comment by deri82** [comment]
Can be closed since there is another report of this

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
