### ISSUE TITLE
MCI 24bit .wav playback on top of pulseaudio (both with winealsa.drv,winepulse.drv) broken

### ISSUE THREAD

**Issue by titan73** [wine-compholio/wine-staging#280]
This is an upstream bug https://bugs.winehq.org/show_bug.cgi?id=37890.

There is a very details explanation in comment 3:
```
This is a bug in wine: wav-file contains 24-bit audio. Pulse-alsa plugin only advertises S16 and S32, no S24 format (see `aplay -v --dump-hw-params -d1 -Ddefault /dev/zero`). When attempting to set it snd_pcm_hw_params_set_format() fails to set S24_3LE, failing winealsa:AudioClient_Initialize. WINMM_OpenDevice catches the fail and calls WINMM_MapDevice to try other rates/formats. 16-bit one succeeds, calling acmStreamOpen, which calls PCM_StreamOpen, which sets cvtKeepRate to one of PCM_ConvertKeepRate[] values. This where things break.

PCM_StreamOpen assumes that wBitsPerSample is either 8 or 16, so it sets conversion to 8->16 bits instead of 24->16 bits that it does not support. When sound plays acmStreamConvert->PCM_StreamConvert->cvtKeepRate->cvtSS816K gets called and turns 24-bit sound into noise.

Attached is a tiny patch for PCM_StreamOpen to fail if format is not 8 or 16-bit. It's not a workaround but it stops wine from producing noise.

The bug never happens with alsa because alsa provides a default=plug->softvol->dmix->hw chain, and its "plug" autoconversion module supports any possible input format, so snd_pcm_hw_params_set_format() never fails and wine's conversion code never gets called.

To reproduce the bug and hear the noise without pulseaudio, using just alsa, you need a "broken" ~/.asoundrc bypassing plug autoconversion and limited supported formats, for example:
pcm.!default {
  type hw
  card 0
  format S16_LE
  rate 44100
  channels 2
}

The workaround for pulseaudio is to fix its alsa-plugin config (usually /usr/share/alsa/alsa.conf.d/pulse.conf or /usr/share/alsa/pulse-alsa.conf or similar) adding "plug" autoconversion there replacing:
pcm.!default {
  type pulse
}
with
pcm.!default {
  type plug

  slave.pcm {
    type pulse
  }
}.
```

This patch http://ix.io/fKz makes the sound correcly by making msacm support conversion for 24 to 16 bit.
I checked native up to version 5.1 but it only support 8 and 16 bit conversions. The latests version is 6.3 but I was not able to use is because it needs plenty of this new dlls that have very long names.
So the question is how windows can get this sound play correctly with a 16 audio device? If it's not in msacm, it is probably elsewhere. Maybe in IAudioClient stuff. So either we add an extension to support 24-bit in msacm or maybe dig a bit to know how it works in Windows and add this conversion to the same place as Windows. What do you think?

**Comment by DarkPlayer** [comment]
Maybe it is not necessary to resample the sound in msacm on Windows? 

On Windows <= XP all sound was passed to the Kernel Mixer ([KMixer](http://en.wikipedia.org/wiki/Windows_legacy_audio_components#KMixer)) which supports resmapling. On Windows >= Vista there is a protected user mode process which is responsible for mixing the audio streams.

I don't know for sure but maybe Windows always fakes 24 bit support and simply uses downsampling while mixing the audio streams?

**Comment by titan73** [comment]
I was guessing something like that. That would be better to leave msacm as is and improve the mixing code to do that. The is mixer in dsound but with this new IAudioClien and mmdevdrv I don't know more how things work together.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
