### ISSUE TITLE
RFE: About 64bit Win binaries support on MacOS 

### ISSUE THREAD

**Issue by oscarbg** [wine-compholio/wine-staging#285]
Hi,
first sorry is this is wrong way to ask support for this..
but just compiled standard wine 1.7.34 and to my surprise seems wine on Mac doesn't support 64bit Win binaries altough on Linux perhaps we have had for some years already.. I know that wine-staging currently doesn't offer MacOS support.. but as this is perhaps the most vibrant wine community right now I'm asking if it would be simple or not to add patches to enable 64bit binaries support on Macs..
If not current beast place to ask where should I ask help for?
thanks..

**Comment by slackner** [comment]
Hi @oscarbg,

the main reason why there is no wine 64-bit version for MacOS yet is that there are various incompatibilities of the Windows 64-bit and MacOS 64-bit ABI (application binary interface).

As you might know Wine is not really emulating any code (with only very few examples), instead it just forwards Windows API calls to their corresponding Linux/MacOS equivalent or provides a wine internal implementation. To provide a fully functional Windows environment Wine has to do various low-level tricks (setting up segment registers, ...) - on MacOS 64-Bit these tricks would conflict with the system libraries. The thread-global "gs"-register for example is used on Windows for the process environment block, on MacOS for thread-local-storage.

That doesn't mean that it is impossible to fix it, but it requires a huge amount of work to do all that correctly. Either system-libraries have to be modified, or compilers would have to generate very special code, ...

There have been various discussions about this topic on mailinglists and on IRC, if you're interested I would recommend to read through them, nevertheless most of it is only understandable when you are familiar with low-level programming and the MacOS internals. See for example: https://www.winehq.org/pipermail/wine-devel/2014-February/103055.html (and following messages)

Since solving the problem properly is really a very difficult task, there also was an attempt to "hack around" the issue recently, see https://www.winehq.org/pipermail/wine-devel/2015-January/106226.html . The idea was to hope that it would work at least for some programs without being fully Windows compatible, but so far the results are not really convincing. I guess a better solution has to be found.

Regards,
Sebastian

**Comment by slackner** [comment]
Closing.
