### ISSUE TITLE
Altium Designer 10 hangs on startup accessing a driver -regression bug-

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#286]
https://bugs.winehq.org/show_bug.cgi?id=34030

Regression SHA1: 	6643f07d2bf8df70490fe6692de1bdf356b4db1e

diff --git a/dlls/ntoskrnl.exe/ntoskrnl.c b/dlls/ntoskrnl.exe/ntoskrnl.c
index 06993ee..03e932c 100644 (file)
--- a/dlls/ntoskrnl.exe/ntoskrnl.c
+++ b/dlls/ntoskrnl.exe/ntoskrnl.c
@@ -197,7 +197,7 @@ static NTSTATUS process_ioctl( DEVICE_OBJECT *device, ULONG code, void *in_buff,
     *out_size = (irp.IoStatus.u.Status >= 0) ? irp.IoStatus.Information : 0;
     if ((code & 3) == METHOD_BUFFERED)
     {
-        memcpy( out_buff, irp.AssociatedIrp.SystemBuffer, *out_size );
+        if (out_buff) memcpy( out_buff, irp.AssociatedIrp.SystemBuffer, *out_size );
         HeapFree( GetProcessHeap(), 0, irp.AssociatedIrp.SystemBuffer );
     }
     return irp.IoStatus.u.Status;

Regression is said to be caused because of that if condition

**Comment by titan73** [comment]
Oh it's me! :s

**Comment by titan73** [comment]
Does the application expects a crash?

**Comment by deri82** [comment]
I am not using that application, never used. 

http://www.altium.com/free-trial but you need to have somekind of login details there to download anything.

Do you know the reason you made that change or why is it wrong?

**Comment by titan73** [comment]
I had a driver passing a null buffer and caused a crash.
There are to possibilities:
- a null out_buff is intentional and the app expect the crash
- the crash compensates another wine problem and preventing it shows another problem
Having a driver test infrastructure is needed to fix things the right way. We don't have it yet although this is planned.

**Comment by slackner** [comment]
I don't think here is anything to fix. I assume the old behaviour was that the driver just crashed and it blocked the corresponding thread from resuming, now it returns and the output is not what it expects. Since ntoskrnl basically only contains stubs so far this is not really surprising.

I agree that we will need to have our driver framework. Will try to take care of this until 1.7.35.

**Comment by deri82** [comment]
Closing for now. Upstream is still open.
