### ISSUE TITLE
Star Wars: The Old Republic - Game Crashes

### ISSUE THREAD

**Issue by Culted** [wine-compholio/wine-staging#291]
swtor is basically unplayable because of multiple crashes 
swtor crashes when hovering over map icon's it crashes when hovering over quest item's
and when trying to do starfighter space pvp the upstream bug is Bug 32092 ( https://bugs.winehq.org/show_bug.cgi?id=32092 )

**Comment by slackner** [comment]
Sorry for the delayed answer, we were setting up our new bugtracker and also cleaning up some other big patchsets during the last days. @DarkPlayer already started to take a look at this. The upstream bug report is very confusing though. Some comments inbetween mention that they can't reproduce the bug anymore, I assume this issue is a bit random and does not always happen immediately?

Nevertheless, we'll report back if we find out any further details.

**Comment by DarkPlayer** [comment]
I don't know yet what is actually going wrong here, but it might be timing related. This would also explain why this problem does not seem to affect everyone.

Nevertheless, if you just want to prevent the crash you can try my evil workaround patch:
https://dl.dropboxusercontent.com/u/61413222/swtor-evil-workaround.diff

The patch allows me to change the settings in game and I can also hover over the icons on the map in the start area. According to the bug report the problem does not happen for all icons, so I can't guarantee that my workaround fixes all problems.

**Comment by Thaodan** [comment]
Thanks I'll apply and try it later and report the results. Which winedebug channels would be usefull to track this down?

**Comment by slackner** [comment]
I don't think there is any particular debug channel that will help, at least not without knowledge where to look for. It most likely needs more manual investigation with  `winedbg` and other tools.

**Comment by Thaodan** [comment]
is there any guide how to too this ?

**Comment by slackner** [comment]
You can find various documents how to use `winedbg`, see for example:
* https://www.winehq.org/docs/winedev-guide/dbg-modes
* https://www.winehq.org/docs/winedev-guide/wine-debugger
* https://www.winehq.org/docs/winedev-guide/dbg-control
Also documents about `dbg` might help sometimes, since `winedbg` is very similar.

Nevertheless, if you are trying to take a look yourself - the most difficult part is to understand whats going on, and this additionally requires knowledge of the assembler programming language and also various tricks you learn over time. Sometimes its also necessary to patch Wine a bit, since various applications will otherwise complain when a debugger is attached.

Please note that we haven't given up solving this bug yet, we'll continue to debug this application after the Wine-Staging 1.7.35 release. The message above was just a quick status update about the current progress.

**Comment by nohatssir** [comment]
I'm really grateful to see that someone is looking into this! Thanks! :)

(Just for reference from the original bugreport). The icons circled with red are the icons that makes it crash for when I hover over them: http://oi46.tinypic.com/j8dyx5.jpg

I tried the dirty patch but it doesn't help for me (well it helps a little because I don't get the divide by zero crash anymore). Directly after the workaround I get a page fault instead.
```
fixme:seh:raise_generic_exception Divide by zero workaround!
wine: Unhandled page fault on write access to 0x00000000 at address 0x7855ae7a (thread 0078), starting debugger...
```
Let me know if I can help with something (as long as I now how to) :)

Thanks again!

**Comment by Zbradaradjan** [comment]
Hello, is there something new on this issue ?

**Comment by JamesChristie** [comment]
@DarkPlayer I tried out that patch against both wine-staging and regular wine last night (1.7.48), and it made zero difference in my ability to mouse over map elements. Also, is this still an appropriate forum for this, or should I open a bug on the new tracker for this issue?

**Comment by DarkPlayer** [comment]
I moved the bug to our new bugtracker: https://bugs.wine-staging.com/show_bug.cgi?id=545
