### ISSUE TITLE
err:d3d:wined3d_debug_callback 0x1bfc4550: "GL_INVALID_OPERATION error generated. Not a valid sampler name.".

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#293]
is bug in game batman arkham origins

err:d3d:wined3d_debug_callback 0x1bfc4550: "GL_INVALID_OPERATION error generated. Not a valid sampler name.".
err:d3d:sampler >>>>>>>>>>>>>>>>> GL_INVALID_OPERATION (0x502) from glBindSampler @ state.c / 3776

**Comment by slackner** [comment]
This was an upstream regression, see https://bugs.winehq.org/show_bug.cgi?id=37912. It is already fixed in wine git.

Please note that we switched to a different [bug tracker](https://bugs.wine-staging.com), and do no longer accept bug reports on this one. As soon as all existing bugs are moved or closed, we will deactivate it. See https://github.com/wine-compholio/wine-staging/issues/292 for more details.
