### ISSUE TITLE
err:xrandr:xrandr12

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#294]
err:xrandr:xrandr12_set_current_mode Resolution change not successful -- perhaps display has changed?
err:xrandr:xrandr12_set_current_mode Resolution change not successful -- perhaps display has changed?
err:d3d:wined3d_swapchain_activate Failed to set display mode.

**Comment by slackner** [comment]
Posting just a couple lines of err's fixme's is not useful. To create a proper bug report we need additional information like:

* which app(s) can be used to reproduce this? if it affects every app it could also be a problem with your window manager
* what is the rest of the terminal output?
* what happens when those err messages appear? is there anything to fix, or are you just wondering?
* more details about your system (wine version, distribution, desktop environment, window manager).

As we do no longer accept bug reports on this bugtracker please create a new one on [bugs.wine-staging.com](https://bugs.wine-staging.com), which additionally includes all the information above. Thanks!
