### ISSUE TITLE
Dealing with these projects work with wine

### ISSUE THREAD

**Issue by Eignar17** [wine-compholio/wine-staging#304]
is project emulator cooperate in project wine-staging is project is use directx and could help but would have to see if convinced to cooperate 

https://github.com/dolphin-emu/dolphin 

https://github.com/PCSX2/pcsx2

could be in agreement

**Comment by Eignar17** [comment]
@slackner @compholio @titan73 @DarkPlayer

**Comment by DarkPlayer** [comment]
see #292.

**Comment by Eignar17** [comment]
not is bug -.- @DarkPlayer  is idea

**Comment by slackner** [comment]
The new bug tracker should be used for all kind of reports - not only bugs, but also for general discussion and patch submission.

Based on a quick look it seems like those applications already exist for Linux. Not sure what your exact idea is, especially because those links are for emulators, which are in no way related to the Windows API.

**Comment by Eignar17** [comment]
cooperation

**Comment by Eignar17** [comment]
my idea is convince those projects for cooperating with the wine as they have an idea of how the directx

**Comment by slackner** [comment]
I am not aware that any of these emulators contains a Direct3D -> OpenGL translation layer, or any other parts which could be useful for Wine itself. What do you mean exactly?

**Comment by Eignar17** [comment]
yes because they have a full understanding on directx and you can convince them to create patches for wine @slackner talk to them to see remaining

**Comment by Eignar17** [comment]
you could contribute to this project @lioncash?

**Comment by Sonicadvance1** [comment]
Thanks for the random name drop.
Does wine even fully support 64bit applications yet?
I don't really care about supporting wine when we fully support Linux.

**Comment by Eignar17** [comment]
for me the important thing is the directx and implementation

**Comment by Eignar17** [comment]
@Sonicadvance1 directx games unfortunately most are irreplaceable and better implementation aria difference

**Comment by Sonicadvance1** [comment]
I don't deal with DirectX, Windows, or x86. I only touch OpenGL, ARMv7, and ARMv8 code in Dolphin. I don't have any plans on working on wine.

**Comment by Eignar17** [comment]
ok Thank you for everything!

**Comment by DarkPlayer** [comment]
@Sonicadvance1 Wine supports 64 bit since quite some time. 

I still don't know what @Eignar17 is trying to achieve. Using Direct3D / OpenGL and writing a Direct3D -> OpenGL wrapper is still a different story. Especially since you need to spend some time to understand the existing wined3d code.

**Comment by Eignar17** [comment]
@DarkPlayer is to implement the missing functions directx or translate to work perfectly in wine

**Comment by DarkPlayer** [comment]
The Direct3D9 implementation of Wine is already in a good shape. The biggest remaining bugs should be fixed by the CSMT. There are still a lot of problems with the d3d9x_* utility libraries, but they can be worked around by using the native dlls.

The real issue is the missing Direct3D10 and Direct3D11 support, but it is unlikely that someone without previous experience in wined3d may work on this. Changing wined3d in a way that it is compatible with D3D9 and D3D10 is very difficult and there are still some problems without a known solution.

**Comment by Eignar17** [comment]
And it's worth to improve wine or as I think is useless. https://github.com/ValveSoftware/ToGL

**Comment by Eignar17** [comment]
Is d3d11 is not works is mesa not works opengl 4.0

**Comment by slackner** [comment]
@Eignar17: Sorry, but this bug tracker is really not the right place to recruit people. This is not the way how you will convince people to join the wine project. This bugtracker is not even the right place at all to start a discussion, see https://github.com/wine-compholio/wine-staging/issues/292! No matter what kind of discussion you want to start, you should do it on our new bug tracker. Wine developers are aware of the Valve ToGL wrapper, and its useless for the wine project. The wine code is much more advanced.
