### ISSUE TITLE
Package for homebrew

### ISSUE THREAD

**Issue by wujekbogdan** [wine-compholio/wine-staging#330]
Thanks for pkg for OS X, but it would be great if there were a package for brew as well. Thanks in advance.

**Comment by slackner** [comment]
Is there any specific reason why you don't like the pkg installers (which do not even need admin rights) or the tarballs? We decided for this approach because we didn't want to rely on any third-party programs or package managers. The idea is that Wine can be installed on a fresh Mac OS X install without any manual effort or long compilation time.

I'm very sorry, but I fear that it currently would be too much effort for us, to maintain Homebrew packages in addition to the WineHQ packages. We also have a couple of other distributions in our queue, where users asked for packages, and those would have a higher priority than OS X, where we already offer at least one solution.

If you are a bit familiar with Homebrew, you could also look into adding a package yourself. Wine Staging is basically just the development version of Wine, with a couple of extra patches. More information is available in our Wiki: https://github.com/wine-compholio/wine-staging/wiki/Packaging. If you need any help, feel free to ask.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
