### ISSUE TITLE
CJK Alternative fonts

### ISSUE THREAD

**Issue by felixonmars** [wine-compholio/wine-staging#8]
The font names were extract from silverlight docs: http://msdn.microsoft.com/en-us/library/cc189010%28VS.95%29.aspx#silverlight_fonts

Font Name | Serif/Sans? | Locale | Popular Alternatives (License)
--------- | --------- | --------- | ---------
Batang | Serif | ko_KR | ?
Meiryo | Sans | ja_JP | **Source Han Sans JP (Apache)**, VL Gothic (custom)
MS Gothic | Sans | ja_JP | Source Han Sans JP (Apache), VL Gothic (custom), IPA Gothic (custom)
MS Mincho | Serif | ja_JP | IPA Mincho (custom)
PMingLiU | Serif | zh_TW | AR PL New Sung (custom:Arphic)
SimSun | Serif | zh_CN | **AR PL SungtiL GB (custom:Arphic)**
Microsoft JhengHei | Sans | zh_TW | **Source Han Sans TWHK (Apache)**
Microsoft YaHei | Sans | zh_CN | **Source Han Sans CN (Apache)**, WenQuanYi Micro Hei (Apache/LGPL)
MingLiu_HKSCS | Serif | zh_HK | AR PL UMing (custom:Arphic)

Note: `AR PL SungtiL GB` is the best alternative to `SimSun` in shape, but may be missing glyphs as it's only a GB2312 font. `AR PL Mingti2L Big5` might be used as a fallback if fallback is possible, and if it's not possible, `AR PL UMing CN` would be covering more glyphs, but contains some nonstandard glyphs for zh_CN readers.

And as I didn't mention in the list, Source Han Sans KR is a sans-serif ko_KR font, it can be used as a last resort for corresponding missing part.

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
