### ISSUE TITLE
Tages Protection v5 needs implementation of MmMapLockedPagesSpecifyCache and IoGetDeviceObjectPointer

### ISSUE THREAD

**Issue by lesebas** [wine-compholio/wine-staging#80]
Hello, 

I've installed wine-compholio to workaround the bug 23033. Even if I don't have anymore message "DLL not found shell.dll16.dll", the tages problem is still there?:

[sebastien@Lupus ~]$ /opt/wine-compholio/bin/wine /home/sebastien/.PlayOnLinux/wineprefix/pearlharbor/drive_c/Program\ Files/Attack\ on\ Pearl\ Harbor/Attack\ on\ Pearl\ Harbor.exe 
fixme:ntoskrnl:KeInitializeTimerEx stub: 0x111280 0
fixme:iphlpapi:NotifyAddrChange (Handle 0xece890, overlapped 0xece89c): stub
wine: configuration in '/home/sebastien/.wine' has been updated.
fixme:ntoskrnl:IoGetCurrentProcess () stub
fixme:ntoskrnl:MmProbeAndLockPages (0x111988, 1, 1): stub
fixme:ntoskrnl:MmMapLockedPagesSpecifyCache (0x111988, 0, 1, (nil), 0, 32): stub
wine: Unhandled page fault on write access to 0x00000000 at address 0x57fe27 (thread 0018), starting debugger...
fixme:ntoskrnl:IoGetCurrentProcess () stub
fixme:ntoskrnl:MmProbeAndLockPages (0x1113f0, 1, 1): stub
fixme:ntoskrnl:MmMapLockedPagesSpecifyCache (0x1113f0, 0, 1, (nil), 0, 32): stub
fixme:ntoskrnl:IoGetDeviceObjectPointer stub: L"\\Device\\atksgt" 20000 0x53e6c8 0x53e6c4
wine: Unhandled page fault on write access to 0x00000004 at address 0x5403c2 (thread 001e), starting debugger...
err:service:service_send_command service protocol error - failed to write pipe!
err:service:service_send_command service protocol error - failed to write pipe!
fixme:ntoskrnl:KeInitializeTimerEx stub: 0x111298 0
fixme:ntoskrnl:IoGetCurrentProcess () stub
fixme:ntoskrnl:MmProbeAndLockPages (0x1113f0, 1, 1): stub
fixme:ntoskrnl:MmMapLockedPagesSpecifyCache (0x1113f0, 0, 1, (nil), 0, 32): stub
fixme:ntoskrnl:IoGetDeviceObjectPointer stub: L"\\Device\\atksgt" 20000 0x53e6c8 0x53e6c4
wine: Unhandled page fault on write access to 0x00000004 at address 0x5403c2 (thread 003c), starting debugger...

**Comment by slackner** [comment]
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.
